### ISSUE TITLE
Update to 01312022 / Automation

### ISSUE THREAD

**Issue by michaeldavie** [m-radzikowski/diagrams-aws-icons#1]
Do you have any plans to update to the latest version, 01312022?

https://d1.awsstatic.com/webteam/architecture-icons/q1-2022/Asset-Package_01312022.735e45eb7f0891333b7fcce325b0af915fd44766.zip

I'd also be happy to help with automating this conversion process, if you haven't done so already.

**Comment by m-radzikowski** [comment]
Hey,
I've finally completed a refactor and published the script I'm using to generate the icons library: [icons-asset-generator](https://github.com/m-radzikowski/icons-asset-generator)

Generating updates should be easier going forward, including also just sending a PR with an update.

I've generated a library for the latest icons pack (2022-04-30) - see in README.

**Comment by michaeldavie** [comment]
Awesome, thanks!
