### ISSUE TITLE
Love the icons, however one big problem

### ISSUE THREAD

**Issue by metaldaniel** [m-radzikowski/diagrams-aws-icons#4]
When I drag them to the canvas in Draw.io they come up without their name, since the description of the shape is not the name of it.
So all shapes come in nameless, could this be added so the shapes come in with the name as it appears in the selection bar?

**Comment by m-radzikowski** [comment]
This would require icons to have labels added. I don't want to add it, as connector lines disappear under them - see https://github.com/jgraph/drawio/issues/1722

Even with labels, they would most likely be too small to be readable in the icons bar.

If you click on "more shapes" there is a checkbox to select to display labels, but icons in the panel are too small and labels show just "Amazon..." or "AWS...".

So I would say that's a UX problem on the diagrams and not something I can fix with the icons library itself. But if you find another library that solves it in a nice way, please let me know. From what I saw, even built-in libraries have the same issue.

When you hover over an icon, it opens a small popup with a bigger icon and its title, and that's the only solution right now.
