### ISSUE TITLE
Feature Request: Organization Group

### ISSUE THREAD

**Issue by Maraket** [m-radzikowski/diagrams-aws-icons#6]
Although I have noted as per the currently open issue (#2 ) that there is manual way to create custom groups, I think it would be prudent to add a Group object for [AWS Organizations](https://aws.amazon.com/organizations/), as for multi-account architectures aren't uncommon and it's a pretty useful feature

**Comment by m-radzikowski** [comment]
The other issue (#2) is about adding groups in general, possibly including the AWS Organizations group. I agree it would be nice to have it and I'll happily review a PR if you are willing to submit one.

**Comment by m-radzikowski** [comment]
Hey, I've added groups in the latest version (2024-02-06). However, I was following the groups that are defined in other resources and have specific icons in the assets, and there is no specific Organizations group there. However, there is an AWS Account group.
