### ISSUE TITLE
Update to 20231023 AWS Icons

### ISSUE THREAD

**Issue by okonon** [m-radzikowski/diagrams-aws-icons#8]
Hi @m-radzikowski would it be possible to update icons to more [recent 2023-10-23 version](https://d1.awsstatic.com/webteam/architecture-icons/q3-2023/Asset-Package_10232023.af3b989c8f30fad5f9c6161440af5cc2f0746e49.zip) ? I attempted to do it on my side but running into an issue while running `icons-asset-generator` on ARM based Mac (could not install Pillow dependency), otherwise i would create a PR for this. Thanks a lot.

**Comment by m-radzikowski** [comment]
I've created a new version with the latest icons (2024-02-06). And also groups!
